# Installation of Arducam Sony IMX219 Camera Modules
# ==================================================

ARG BASE=nvcr.io/nvidia/l4t-base:r32.5.0
FROM $BASE

ENV DEBIAN_FRONTEND="noninteractive"

# gstreamer
# ---------

RUN apt-get update \
&&  apt-get install -y \
    gstreamer1.0-tools \
    gstreamer1.0-alsa \
    gstreamer1.0-plugins-base \
    gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad \
    gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav \
    libgstreamer1.0-dev \
    libgstreamer-plugins-base1.0-dev \
    libgstreamer-plugins-good1.0-dev \
    libgstreamer-plugins-bad1.0-dev \
&&  apt-get autoremove -y \
&&  rm -rf /var/lib/apt/lists/*

# View Imagery
# gst-launch-1.0 nvarguscamerasrc sensor-id=0 ! 'video/x-raw(memory:NVMM),width=3264, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw, width=816, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e
# gst-launch-1.0 nvarguscamerasrc sensor-id=1 ! 'video/x-raw(memory:NVMM),width=3264, height=2464, framerate=21/1, format=NV12' ! nvvidconv flip-method=0 ! 'video/x-raw, width=816, height=616' ! nvvidconv ! nvegltransform ! nveglglessink -e

# v4l-utils
# ---------

RUN apt-get update \
&&  apt-get install -y \
    v4l-utils \
&&  apt-get autoremove -y \
&&  rm -rf /var/lib/apt/lists/*

# List all video devices
# v4l2-ctl --list-devices

# Query a video device’s information
# v4l2-ctl -d0 -D

CMD ["bash"]






